### PR TITLE
Master

### PR DESCRIPTION
**Pull request by Jeremy-Jia**
change title 2022.7.10

### CODE REVIEW

**Comment by Jeremy-Jia** [comment]
change title

**Comment by Jeremy-Jia** [comment]
11111111

**Comment by Jeremy-Jia** [comment]
Suggested edit:
```diff
diff --git a/.vscode/settings.json b/.vscode/settings.json
new file mode 100644
index 0000000..9e26dfe
--- /dev/null
+++ b/.vscode/settings.json
@@ -0,0 +1 @@
+{}
\ No newline at end of file
diff --git a/donate.html b/donate.html
index 3858006..066921a 100644
--- a/donate.html
+++ b/donate.html
@@ -1,7 +1,7 @@
 <!DOCTYPE HTML>
 <html>
 	<head>
-		<title>Untitled</title>
+		<title>宝宝我爱你</title>
 		<meta charset="utf-8" />
 		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
 		<link rel="stylesheet" href="assets/css/main.css" />
@@ -31,7 +31,7 @@
 						<span style="display: flex; position: fixed; top: 2em; left: 2em; opacity: 0.65;" v-if="backButton"><button class="button small" onclick="toIndex()">&lt;返回</button></span>
 						<header>
 							<span class="avatar"><img src="images/avatar.jpg" alt="" style="width: 122px; height: 122px;" /></span>
-							<h1>Untitled</h1>
+							<h1>宝宝我爱你</h1>
 							<transition-group name="fade">
 								<div v-html="text" v-show="defaults" key="text"></div>
 								<div v-for="item in method" v-show="item.show" key="item.name" v-html="item.content"></div>
diff --git a/footer.html b/footer.html
index 7dab5ae..ce11232 100644
--- a/footer.html
+++ b/footer.html
@@ -1,6 +1,6 @@
 <ul class="copyright" style="opacity: 0.5;">
-    <li><a href="#">&copy; Untitled</a></li><li><small>Design: <a href="http://html5up.net" target="_blank">HTML5 UP</a></small></li><li>Background: <a href="http://unsplash.com" target="_blank">Unsplash</a></li>
+    <li><a href="#">&copy; 宝宝我爱你</a></li><li><small>Design: <a href="http://html5up.net" target="_blank">HTML5 UP</a></small></li><li>Background: <a href="http://unsplash.com" target="_blank">Unsplash</a></li>
 </ul>
 <ul class="copyright" style="opacity: 0.5;">
-    <li>Untitled</li><li><a href="https://beian.miit.gov.cn/" target="_blank">备案号</a></li>
+    <li>宝宝我爱你</li><li><a href="https://beian.miit.gov.cn/" target="_blank">备案号</a></li>
 </ul>
\ No newline at end of file
diff --git a/index.html b/index.html
index 1fbade4..61c5058 100644
--- a/index.html
+++ b/index.html
@@ -1,7 +1,7 @@
 <!DOCTYPE html>
 <html>
   <head>
-    <title>Untitled</title>
+    <title>宝宝我爱你</title>
     <meta charset="utf-8" />
     <meta
       name="viewport"
@@ -60,7 +60,7 @@
               alt=""
               style="width: 122px; height: 122px"
           /></span>
-          <h1>Untitled</h1>
+          <h1>宝宝我爱你</h1>
           <transition-group name="fade">
             <div v-show="defaults" key="text">
               <p>Lorem</p>
diff --git a/pay.html b/pay.html
index 4dafa34..25a688e 100644
--- a/pay.html
+++ b/pay.html
@@ -1,7 +1,7 @@
 <!DOCTYPE HTML>
 <html>
 	<head>
-		<title>Untitled</title>
+		<title>宝宝我爱你</title>
 		<meta charset="utf-8" />
 		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
 		<link rel="stylesheet" href="assets/css/main.css" />
diff --git a/qr.html b/qr.html
index fe86b6d..49db20e 100644
--- a/qr.html
+++ b/qr.html
@@ -1,7 +1,7 @@
 <!DOCTYPE HTML>
 <html>
 	<head>
-		<title>Untitled</title>
+		<title>宝宝我爱你</title>
 		<meta charset="utf-8" />
 		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
 		<link rel="stylesheet" href="assets/css/main.css" />
@@ -31,7 +31,7 @@
 						<span style="display: flex; position: fixed; top: 2em; right: 2em; opacity: 0.65; font-size: 0.8em;"><button class="button small" @click="screenShot" id="screenshot">保存网页截图</button></span>
 						<header>
 							<span class="avatar"><img src="images/avatar.jpg" alt="" style="width: 122px; height: 122px;" /></span>
-							<h1>Untitled</h1>
+							<h1>宝宝我爱你</h1>
 						</header>
 						<h1>站内二维码生成</h1>
 						<div>

```

**Comment by Jiaocz** [comment]
Please do not submit your personal change.
Reopen if it necessary.
BTW your real name seems leaked.

**Comment by Jiaocz** [comment]
And please, **DO NOT** remove the origin link or quote to this repo, or you're violating the license.

**Pull request closed without merging**
